### ISSUE TITLE
Inverted density gradients ...

### ISSUE THREAD

**Issue by AndyHoggANU** [angus-g/python-ale#12]
It turns out that our test case has some regions near the surface where the temperature gradient is inverted and it's causing problems. The image below shows the issue -- close to the surface we get reduced isopycnal slope which sends the adaptive coordinate back into isopycnal mode:

<img width="1079" alt="Screenshot 2024-04-11 at 10 55 53 AM" src="https://github.com/angus-g/python-ale/assets/26753100/cfde1616-1853-4969-a04f-9fb85fb5deb3">

The simple fix for this is to place a condition on vertical density gradient to ensure it never gets below epsilon ...

**Comment by AndyHoggANU** [comment]
Err, I think there might be a sign error here. Slope is now set to unity throughout the interior ...
![Uploading Screenshot 2024-04-25 at 11.10.11 AM.png…]()

**Comment by angus-g** [comment]
Hmm, that's weird! Maybe try again now with the flipped signs?

**Comment by AndyHoggANU** [comment]
Yeah, that's better.

**Comment by AndyHoggANU** [comment]
<img width="1088" alt="Screenshot 2024-04-25 at 11 32 28 AM" src="https://github.com/angus-g/python-ale/assets/26753100/885c9072-3f2a-456b-8ab2-f9010341e5ff">

**Comment by AndyHoggANU** [comment]
On more thing here. The diagnostic of slope seems to be set to zero in the top layer. Is there a boundary condition set on the vertical gradient of density? It might be best to set that boundary condition to be zero gradient, which should force a finite slope at the surface (and hopefully it will be 1 there)

**Comment by AndyHoggANU** [comment]
Just looked at the code re the slope calculation near the surface - it's not clear to me that the `k=1` case is computed? Is this because we don't evolve the surface interface or is it an omission?

**Comment by angus-g** [comment]
> Just looked at the code re the slope calculation near the surface - it's not clear to me that the `k=1` case is computed? Is this because we don't evolve the surface interface or is it an omission?

The former. Regridding is not allowed to change the total column thickness, so `k=1` and `k=nz+1` must remain as they are.

**Comment by AndyHoggANU** [comment]
Aah, OK, so this is only an issue in the non-time stepping version of the pyale code?

**Comment by angus-g** [comment]
I guess the slope is actually calculated along *interfaces*, so I don't quite know how you would extend that to a layerwise value.

**Comment by AndyHoggANU** [comment]
Yeah, I guess my worry here is that there are some latitudes where no interfaces have large slope, which doesn't make sense to me ...
