### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by AndyHoggANU** [angus-g/python-ale#8]
Running pyale in a Jupyter notebook, I've had trouble with some kernels dying. This seems to happen when I run `pyale.accelerate_ale` multiple times, or when I run `pyale.accelerate_ale` followed by `pyale.resume_ale`. It's inconsistent, in the number of times it takes to fail ...

A script I'm having trouble with is this one, where I'm trying to step through the evolution of the adaptive coordinate:
https://github.com/AndyHoggANU/anu-tub/blob/master/diagnostics/AG_Test_Resume.py

**Comment by angus-g** [comment]
Where is the `INPUTS` directory for this so I can grab the `MOM.res.nc`? Will have a dig into it...

**Comment by AndyHoggANU** [comment]
`/g/data/x77/amh157/anu-tub/diagnostics/INPUTS`

**Comment by angus-g** [comment]
Good catch here, should be closed by 8bb9023 now! I'll update the build on Gadi, and look at the zeroed out diagnostics now.
